### ISSUE TITLE
There is no PHP code in the repo

### ISSUE THREAD

**Issue by anatoliyarkhipov** [prezly/prop-types-php#1]
The README states that's a complete PHP port of React PropTypes, but there is no PHP code in the repository.

Probably I misunderstood and it's a complete port of _production_ React PropTypes, which don't exist? 🤔

**Comment by e1himself** [comment]
Привіт, @anatoliyarkhipov :wave:

> a complete port of production React PropTypes

:joy: 

-------------

Jokes apart. Sorry, I had some code locally, but didn't push it as not all of PropTypes were ready at the moment.

Anyway, I've pushed everything I have and updated the Readme to provide an overview of the current development progress.

I'll try to finish the missing checkers in the upcoming days.

**Comment by anatoliyarkhipov** [comment]
Ha-ha, thanks for the fast reaction 😁.

Don't feel obligated to finish them ASAP, or something like that. I'm thankful for what you've already done & published.

Can you also share some use-cases, do you use the lib in a project? My use-case is that I need to validate some plain-array structures passed around between different services.

**Comment by e1himself** [comment]
> Can you also share some use-cases, do you use the lib in a project? My use-case is that I need to validate some plain-array structures passed around between different services.

No, we don't use it yet. But I've created this repo because I wanted to start using it :)

The main use-case I had in mind is the same use-case JS PropTypes are solving: add complex structure assertions to validate methods arguments (i.e. development assertions). Though it can also be used for validating API input structures, it's not tailored for that case, as the checks do not (and will not) allow providing friendly user-facing errors.
